sonar.projectKey=Finance-APP
sonar.projectName=Finance APP
sonar.projectVersion=1.0
sonar.sources=.
sonar.inclusions=**/*.html,**/*.js,**/*.css
sonar.exclusions=node_modules/**,k8s/**,**/*.test.js
sonar.sourceEncoding=UTF-8
