apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-app
  template:
    metadata:
      labels:
        app: finance-app
    spec:
      containers:
      - name: finance-app
        image: finance-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80